* Coding Standards
The Perseus6 project follows minimal computing standards:

1. The system must be /stable/: it shold not rely execessively on external libraries or frameworks.

2. The system must be /sustainable/: it should have a clean architecture based on modern software design principles.

3. The system must be /maintainable/: Experienced developers should be able to understand it readily; it should be properly documented; it should have good test coverage.

Following minimal-computing principles, most of the Perseus 6 code is written in Python, XQuery, and XSLT, because these are the most commonly used programming languages in Perseus's community of developers.


** Python Guidelines
- Prefer the latest stable version of Python unless there are conflicts with dependencies. The current stable release is Python 3.14.3, which contains the latest performance optimizations and security patches as of this writing.

- Use [[https://pdm-project.org/en/latest/][PDM]] to manage dependencies. Configure PDM to use [[https://docs.astral.sh/uv/][uv]].
- Use the [[https://docs.pytest.org/en/stable/][pytest]] framework for testing.

*** Programming Paradigms
- Use Object-Oriented Programming methods and techniques.
- Use dependency injection to reduce coupling.
- Follow [[https://en.wikipedia.org/wiki/SOLID][SOLID principles]].
- Follow [[https://peps.python.org/pep-0008/][PEP 8]].

*** Deployment
- Use GitHub Actions to manage workflows
