* P4 Analysis
This analysis sets the scope of the implementation. Many capabilities have been explored since P4 was deployed, and they have been demonstrated in the Scaife Viewer and Beyond Translation prototypes. Taking those capabilities beyond the prototype stage, however, is beyond the scope of this project's first phase.

** P4 Functional Components
*** Catalog
P4 implements a crude collection-based catalog

*** Tools

**** Search Tools

**** Named Entity Search Tools

*** Reading Environment
At the top is a /browse bar/, a visual aid to seeing your place in the text, by chunk.

The main part of the page is split into three columns. On the left and right are widgets providing various functions:

- This text is part of
- View text chunked by
- Table of Contents
- Search
- Display Preferences
- Translations
- References
- Vocabulary Tool
- Search
- Stable Identifiers

The center column is the reader proper. It has forward and backward buttons at the top, as well as a navigate-by-citation box. Below them is the actual text.

Non-English texts have been tokenized, with links to word-study tools.


*** Reading environment requirements for P6 (static version)

- Search
- Translations
- Vocabulary tool
- Cross-refs and other references


** Code Base Analysis
A preliminary analysis of the P4 code base, downloaded from SourceForge and added to this repository as /perseus-hopper/, provides a framework for scoping our work.

*** Focusing on Texts
In the first phase we will focus solely on the text reading environment.

*** We will not re-implement Art & Archaeology handling
That collection is already being handled by a different, RDF-based system.

The code is in ~reading/src/perseus~
*** src/perseus
