* Perseus6
A reading environment that replaces Perseus 4 (the Hopper).

** Background
The Perseus Digital Library is a large collection of texts encoded in TEI XML. These encoded texts are Open Source and available on [GitHub](https://github.com/PerseusDL). Perseus has always provided tools for discovering resources and reading them in a richly hypertextual environment. Perseus6 is an implementation of those tools.

** Minimal Computing
Perseus6 follows the principles of /minimal computing/, which advocate lightweight web design and reduced complexity.

Perseus6 relies on external services to supplement its minimal capabilities with full-text searching, metadata faceting, and on-demand linguistic processing and analysis, all of which require web-accessible database systems that Perseus can no longer provide.  Instead, Perseus6 is /data forward/:  Perseus provides the data and the software that allow users with computation resources to create services.

** Components
Perseus6 is a software system for processing, discovering, searching, and reading digital texts.

*** Processing
Perseus6 includes several compilers:

- a program that takes TEI-encoded XML documents and generates HTML pages that can be read without JavaScript

- a program that compiles catalogs, citation tables, and other files that define links.

- a program that compiles vocabulary aids for Greek and Latin texts.

- a program that generates passage-level alignments.

*** Discovering
Perseus6 includes a simple catalog for finding texts and translations using link-following and in-browser searches. It is not a full-fledged discovery system because Perseus6 has no back-end database system.


*** Reading
Perseus6 does not have a /reading environment/ as prior versions did; its compiled HTML pages may be viewed and navigated using a basic web browser.  Full-text search is not included in the Perseus6 reader. Instead, it provides a website that serves hypertextually linked HTML files via simple HTTP.


** What this Repository Contains
This GitHub repository contains the code for the analyzers and compilers that generate Perseus6's website.


** Documentation

See the wiki associated with this repository for standards, workflows, and best practices used in this project.

Following minimal-computing principles, most of the code is written in Python, because Python is the most commonly used programming language in Perseus's community of developers.

Following contemporary best practices, the code is designed to avoid external dependencies. It is built on Python 3.14.3, the latest stable release, which contains the latest performance optimizations and security patches as of this writing.
