* Perseus 6 Design

* Minimal Computing
Perseus6 follows the principles of /minimal computing/, which advocate lightweight web design and reduced complexity.

** MVP: The Perseus 6 Core
The core of Perseus 6 is a static website called Minimum Viable Perseus (MVP) comprising linked HTML documents compiled from TEI-encoded XML files and other resources. We aim to make the core adhere to the [[https://www.w3.org/standards/][W3C's Web Standards]], in order to make it stable, maintainable, and accessible.  MVP's web pages are built entirely with modern HTML and CSS; following the [[https://github.com/aarontgrogg/NoLoJS][NoLoJS philosophy]], they employ little to no Javascript.

** External Components
Perseus6 relies on external services to supplement its minimal capabilities with full-text searching, metadata faceting, and on-demand linguistic processing and analysis, all of which require web-accessible database systems that Perseus can no longer provide.  Instead, Perseus6 is /data forward/:  Perseus provides the data and the software that allow users with computation resources to create services.

** Processors
Perseus6 includes several compilers:

- a program that takes TEI-encoded XML documents and generates HTML pages that can be read without JavaScript

- a program that compiles catalogs, citation tables, and other files that define links.

- a program that compiles vocabulary aids for Greek and Latin texts.

- a program that generates passage-level alignments.

** Components of Perseus 6 Core

*** Discovering

MVP includes a simple catalog for finding texts and translations using link-following and in-browser searches, but because it has no dynamc backend database or indexes, MVP lacks sophisticated search and retrieval features common in modern digital library systems. Instead, it delegates search and discovery to external systems like search engines and AI research systems.


*** Reading

MVP does not have a reading environment /per se/, as prior versions did; its compiled HTML pages may be viewed and navigated using a basic web browser, but there are no features that would rely on communication with a running backend process or database.  Full-text search is not included in the Perseus6 reader. Instead, it provides a website that serves hypertextually linked HTML files via simple HTTP.



** Documentation

See the wiki associated with this repository for standards, workflows, and best practices used in this project.
